image: mcr.microsoft.com/dotnet/core/sdk
stages:
  - build
  - test
  - publish
build:
 stage: build
 script:
  - 'dotnet restore FoodOrder'
  - 'dotnet build'
test:
 stage: test
 script:
  - 'dotnet test TestProject/TestProject.csproj'
publish:
 stage: publish
 script:
  - 'dotnet publish'
