image: mcr.microsoft.com/dotnet/core/sdk
stages:
  - build
  - test
  - publish
build:
 stage: build
 script:
  - 'dotnet restore UsersMicroservice/UsersMicroservice.csproj'
  - 'dotnet restore RestaurantAPI/RestaurantAPI.csproj'
  - 'dotnet restore PromotionCode/PromotionCode.csproj'
  - 'dotnet restore OrderFood web API/OrderFood web API.csproj'
  - 'dotnet build'
test:
 stage: test
 script:
  - 'dotnet test TestProject/TestProject.csproj'
publish:
 stage: publish
 script:
  - 'dotnet publish'
