image: mcr.microsoft.com/dotnet/core/sdk
stages:
  - build
  - publish
build:
 stage: build
 script:
  - 'dotnet restore ./UsersMicroservice/'
  - 'dotnet build'
publish:
 stage: publish
 script:
  - 'dotnet publish'
