version: '3.5'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=pass@123
      - ACCEPT_EULA=Y

  restaurantapi:
    image: restaurantapi
    ports:
      - "5002:80"
    environment:
      Mongo_DB: "mongodb://db:27017"
      DB_Name: "RestaurantDb"
    depends_on:
      - db
      - apigateway

  users:
    image: users
    ports:
      - "5001:80"
    environment:
      SQL_DB: "Data Source=sqlserverdb;Initial Catalog=UsersDB;User Id=sa;Password=pass@123"
    depends_on:
      - sqlserverdb
      - apigateway
  
  promotioncode:
    image: promotioncode
    ports:
      - "5003:80"
    environment:
      SQL_DB: "Data Source=sqlserverdb;Initial Catalog=PromotionCodeDB;User Id=sa;Password=pass@123"
    depends_on:
      - sqlserverdb
      - apigateway
  
  orderfoodapi:
    image: orderfoodapi
    ports:
      - "5004:80"
    environment:
      Mongo_DB: "mongodb://db:27017"
      DB_Name: "OrderFoodDB"
    depends_on:
      - db
      - apigateway
  
  apigateway:
    image: apigateway
    ports:
      - "5005:80"